[package]
name = "dk_agents"
version = "0.1.0"
edition = "2021"

[dependencies]
dk_core = { path = "../dk_core" }
dk_raws = { path = "../dk_raws" }
dk_world = { path = "../dk_world" }
dk_sim = { path = "../dk_sim" }
serde = { workspace = true }
bincode = { workspace = true }
anyhow = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
